### ISSUE TITLE
AssertionError: La opción de agrupar por día no funciona: expected undefined to exist

### ISSUE THREAD

**Issue by JoseNotFound** [antonioroig/practica_dwec_gestor_presupuesto#44]
Este es el error del cual me dijiste que te crease un issue.

**Comment by antonioroig** [comment]
Normalmente en el issue debes ponerme la salida del error copiada o arrastrando y soltando una captura de pantalla.

**Comment by antonioroig** [comment]
Tu método obtenerPeriodoAgrupacion, cuando se le pasa como periodo día, no funciona correctamente. No produce la cadena adecuada. Aunque te haya pasado el test anterior, ahora sale el error y debes revisarlo y corregirlo.
